#!/bin/sh
# From https://github.com/faisyl/alpine-runit
env > /etc/envvars

/etc/rc.local
retval=$?
if [ $retval -ne 0 ];
then
    echo >&2 "[ERROR] Calico node failed to start normally..."
    echo "[WARN] Attempting to start Calico node in failsafe mode"
    . startup.env
    exec /sbin/runsvdir -P /etc/service/enabled || exit $retval
    echo "[WARN] Started Calico node in failsafe mode."
fi

# Source any additional environment that was added by the startup script
. startup.env

exec /sbin/runsvdir -P /etc/service/enabled
